In [3]:
a=[10,20,3]
println(typeof(a))

Vector{Int64}


In [5]:
b=[10 30 42]
println(typeof(b))

Matrix{Int64}


In [7]:
typeof(randn(10))

Vector{Float64} (alias for Array{Float64, 1})

In [11]:
@show ndims(a)
@show size(a)

ndims(a) = 1
size(a) = (3,)


(3,)

In [2]:
@show zeros(4)

zeros(4) = [0.0, 0.0, 0.0, 0.0]


4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [7]:
zeros(2,2)

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [9]:
fill(5,2,2)

2×2 Matrix{Int64}:
 5  5
 5  5

In [11]:
x=[1 2 3]
y=similar(x,2,2)

2×2 Matrix{Int64}:
 493657952  493243288
 493121288          0

In [15]:
a=[10,20,3,1]
ndims(a)

1

In [17]:
a=[10 2 3 4]
ndims(a)

2

In [19]:
a=[10 20 30 40]
@show a


a = [10 20 30 40]


1×4 Matrix{Int64}:
 10  20  30  40

In [1]:
b=a'
@show b

LoadError: UndefVarError: a not defined

In [4]:
a=[1 2;3 4]
@show a
b=a[:,2]
@show b

a = [1 2; 3 4]
b = [2, 4]


2-element Vector{Int64}:
 2
 4

In [7]:
a=[1 2 ;3 4]
@show a


a = [1 2; 3 4]


2×2 Matrix{Int64}:
 1  2
 3  4

In [10]:
x=[2 3 4]

1×3 Matrix{Int64}:
 2  3  4

In [14]:
y=x

1×3 Matrix{Int64}:
 2  3  4

In [18]:
x[1]=100

100

In [13]:
using StaticArrays
xdynamic=[1,2]

2-element Vector{Int64}:
 1
 2

In [17]:
xstatic=@SVector [1,2]
f(x)=2x
@show xdynamic
@show f(xdynamic)
@show xdynamic

xdynamic = [2, 4]
f(xdynamic) = [4, 8]
xdynamic = [2, 4]


2-element Vector{Int64}:
 2
 4

In [8]:
@show f(xstatic)

f(xstatic) = [2, 4]


2-element SVector{2, Int64} with indices SOneTo(2):
 2
 4

In [15]:
function g(x)
    x.=2*x
    return "sucess!"
end
@show xdynamic
@show g(xdynamic)
@show xdynamic

xdynamic = [1, 2]
g(xdynamic) = "sucess!"
xdynamic = [2, 4]


2-element Vector{Int64}:
 2
 4

In [21]:
@show g(xstatic)

LoadError: setindex!(::SVector{2, Int64}, value, ::Int) is not defined.

In [27]:
using Statistics
a=[-1 ,0,1]
@show length(a)
@show maximum(a)
@show extrema(a)
@show std(a)
@show var(a)

length(a) = 3
maximum(a) = 1
extrema(a) = (-1, 1)
std(a) = 1.0
var(a) = 1.0


1.0

In [33]:
a=[-1,0,1]
b=sort(a,rev=true)
@show b
@show a===b

b = [1, 0, -1]
a === b = false


false

In [35]:
b=sort!(a,rev=true)
@show b
@show b===a


b = [1, 0, -1]
b === a = true


true

In [40]:
a=ones(1,2)
b=ones(2,2)
@show a*b

a * b = [2.0 2.0]


1×2 Matrix{Float64}:
 2.0  2.0

In [46]:
@show b*a'

b * a' = 

2×1 Matrix{Float64}:
 2.0
 2.0

[2.0; 2.0]


In [48]:
a=randn(4)

4-element Vector{Float64}:
 -1.2330319249658137
  0.1780449859853845
 -0.4266220905381039
  0.5218684056166425

In [50]:
a.>0

4-element BitVector:
 0
 1
 0
 1

In [52]:
a[a .<0]

2-element Vector{Float64}:
 -1.2330319249658137
 -0.4266220905381039

In [55]:
b= [1 3 4]
a=[3 2 5]
b.> a

1×3 BitMatrix:
 0  1  0

In [57]:
a=[10,20,30,40]
b=reshape(a,2,2)
@show b


b = [10 30; 20 40]


2×2 Matrix{Int64}:
 10  30
 20  40

In [59]:
a

4-element Vector{Int64}:
 10
 20
 30
 40

In [64]:
a=[1 2 3 4]
@show a
@show typeof(a)
reshape(a,2,2)

a = [1 2 3 4]
typeof(a) = Matrix{Int64}


2×2 Matrix{Int64}:
 1  3
 2  4