In [3]:
using BenchmarkTools

function col_iter(x)
    s=zero(eltype(x))
    for j in 1:size(x,2)
        for i in 1:size(x,1)
            s=s+x[i,j]^2
            x[i,j]=s
        end
    end
end

function row_iter(x)
    s=zero(eltype(x))
    for  i in 1:size(x,1)
        for j in 1:size(x,2)
            s=s+x[i,j]^2
            x[i,j]=s
        end
    end
end
@show row_iter(rand(2,2))
@show col_iter(rand(2,2))

row_iter(rand(2, 2)) = nothing
col_iter(rand(2, 2)) = nothing


In [5]:
a=rand(10000,10000)
@btime col_iter($a)
@btime row_iter($a)
#adjoint
b=a'
@btime col_iter($b)
@btime row_iter($b)

  195.446 ms (0 allocations: 0 bytes)
  1.379 s (0 allocations: 0 bytes)
  2.013 s (0 allocations: 0 bytes)
  134.580 ms (0 allocations: 0 bytes)


In [10]:
@btime fill(1,1000,1000)
@btime Array{Int64}(undef,1000,1000)



  2.864 ms (2 allocations: 7.63 MiB)
  18.400 μs (2 allocations: 7.63 MiB)


1000×1000 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0

In [1]:
a=Array{Int64}(undef,4,4)


4×4 Array{Int64,2}:
 0         4294967296  72339069014638592  1099511693312
 0      1099528470529                  1          65536
 0    281474993488128                  0              0
 0  72339069014704385      1099511627776              0

In [4]:
using BenchmarkTools
function sum_vector(x::Array{Float64,1})
    s=zero(eltype(x))
    for i in 1:length(x)
        s=s+x[i]
        
    end
    return s
end

function sum_cols_matrix(x::Array{Float64,2})
    num_cols=size(x,2)
    s=zeros(num_cols)
    for i in 1:num_cols
        s[i]=sum_vector(x[:,i])
    end
    return s

end

a=rand(10,10)
sum_cols_matrix(a)


10-element Array{Float64,1}:
 4.765326237104522
 3.50490222596528
 4.837520261863569
 4.716763521744596
 5.527452503674673
 5.193431256523979
 3.3881815041421017
 4.87777440925035
 4.906543237700056
 5.622587999422724

In [7]:
a=rand(1000,1000)
@benchmark sum_cols_matrix(a)

BenchmarkTools.Trial: 
  memory estimate:  7.76 MiB
  allocs estimate:  1001
  --------------
  minimum time:     2.156 ms (0.00% GC)
  median time:      2.719 ms (0.00% GC)
  mean time:        4.115 ms (7.68% GC)
  maximum time:     51.218 ms (48.37% GC)
  --------------
  samples:          1218
  evals/sample:     1